name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install

      - name: 💅 Lint code
        run: bun run lint:fix

      - name: 📚 Build docs
        run: bun run automd

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
        with:
          commit-message: 'chore: apply automated lint fixes'
