name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install

      - name: 💅 Lint code
        run: bun run lint

      - name: 🧪 Run tests
        run: bun run test

      - name: 🤖 Build
        run: bun run build

  release:
    needs: ci
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1
        with:
          bun-version: latest

      - name: 📦 Install dependencies
        run: bun install

      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@63bc5b97aade4390bf3f33416b8adb891a0f28d7' # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: 'feat,Adds,minor,add'
          major-wording: 'BREAKING CHANGE,remove,Removes,major'
          patch-wording: 'fix,Fixes,bugfix'
          rc-wording: 'RELEASE,alpha'
          tag-prefix: 'v'
          commit-message: 'chore(release): Bump version to {{version}}'

      - name: 🚀 Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc &&
          npm publish --provenance

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: 🚢 GitHub Release
        run: bunx changelogen gh release --token ${{ secrets.GITHUB_TOKEN }}
